### ISSUE TITLE
Failure when building with olca-modules 1.7.4

### ISSUE THREAD

**Issue by lucas1993** [GreenDelta/olca-conversion-service#8]
I am having an issue when building with the latest version (1.7.4) of olca-modules, built from GreenDelta/olca-modules. I have changed olca-conversion-service/pom.xml <olca.version> tag to 1.7.4.

There are some incompatible function names and types. Build log bellow:

>[INFO] ------------------------------------------------------------------------
>[INFO] BUILD FAILURE
>[INFO] ------------------------------------------------------------------------
>[INFO] Total time: 11.817 s
>[INFO] Finished at: 2018-11-29T09:30:04-02:00
>[INFO] Final Memory: 52M/285M
>[INFO] ------------------------------------------------------------------------
>[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.2.31:compile (compile) on project olca-conversion-service: Compilation failure: Compilation failure:
>[ERROR] /home/amaral/Documents/ibict/sciv/olca-conversion-service/src/main/kotlin/app/model/ImportILCD.kt:[24,13] Unresolved reference: importProcess
>[ERROR] /home/amaral/Documents/ibict/sciv/olca-conversion-service/src/main/kotlin/app/model/ImportSimaProCsv.kt:[22,40] Type mismatch: inferred type is File but Array<(out) File!>! was expected
>[ERROR] /home/amaral/Documents/ibict/sciv/olca-conversion-service/src/main/kotlin/app/model/LcaRepo.kt:[16,1] Class 'LcaRepo' is not abstract and does not implement abstract member public abstract fun putMetaInfo(p0: JsonObject!): Unit defined in org.openlca.jsonld.EntityStore
>[ERROR] -> [Help 1]
>[ERROR] 
>[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
>[ERROR] Re-run Maven using the -X switch to enable full debug logging.
>[ERROR] 
>[ERROR] For more information about the errors and possible solutions, please read the following articles:
>[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by msrocka** [comment]
updated it to olca-modules 1.11.0, which are on the Maven Central repository, finally
